# platform :ios, '8.0'

target 'FSWB' do

use_frameworks!

pod 'AFNetworking' , '~> 3.1.0'
pod 'SDWebImage' , '~> 3.8.2'
pod 'YYModel' , '~> 1.0.4'
pod 'SVProgressHUD' , '~> 2.1.2'
pod 'pop' , ' ~>1.0.9'

end
